before @mixin

diff --git a/mulle-objc-deps-tool b/mulle-objc-deps-tool
--- a/mulle-objc-deps-tool
+++ b/mulle-objc-deps-tool
@@ -485,6 +485,8 @@ main()
    #
    PATH="${PATH}:${DEPENDENCY_DIR}/bin"
 
+
+
    local name
 
    name="$1"
@@ -558,7 +560,12 @@ Is whole archive load working on this platform ?"
    local directory
 
    r_mkdir_parent_if_missing "${OUTPUT}" || exit 1
+   if [ -f "${OUTPUT}" ]
+   then
+      exekutor chmod a+w "${OUTPUT}" || fail "Can't unprotect \"${OUTPUT}\""
+   fi
    redirect_exekutor "${OUTPUT}" echo "${result}" || exit 1
+   exekutor chmod a-w "${OUTPUT}"
    log_info "Wrote \"${OUTPUT}\""
 }
 
