* fixes for mingw

diff --git a/mulle-objc-create-dependencies-inc b/mulle-objc-create-dependencies-inc
--- a/mulle-objc-create-dependencies-inc
+++ b/mulle-objc-create-dependencies-inc
@@ -232,15 +232,6 @@ main()
             usage
          ;;
 
-         --no-remove)
-            OPTION_REMOVE_TMP="NO"
-         ;;
-
-         -f|--force)
-            OPTION_FORCE="YES"
-         ;;
-
-
          -b|--build-path)
             [ $# -eq 1 ] && usage
             shift
@@ -248,8 +239,16 @@ main()
             BUILDPATH="$1"
          ;;
 
+         -f|--force)
+            OPTION_FORCE="YES"
+         ;;
+
          -n|--dry-run)
             MULLE_FLAG_EXECUTOR_DRY_RUN="YES"
+         ;;
+
+         --no-remove)
+            OPTION_REMOVE_TMP="NO"
          ;;
 
          -o|--output)
@@ -279,8 +278,6 @@ main()
    core_setup_trace "${MULLE_TRACE}"
    export MULLE_TRACE
 
-   eval `mulle-bootstrap paths path` || fail "mulle-bootstrap not found"
-
    local name
 
    name="$1"
@@ -309,14 +306,20 @@ main()
       ;;
    esac
 
+   local pathcmd
+
+   pathcmd="`mulle-bootstrap paths -s ':' -q "'" path`" || fail "mulle-bootstrap not found in PATH ($PATH)"
+
+   eval "${pathcmd}" 
+
    if [ -z "`command -v "mulle-objc-list"`" ]
    then
-      fail "mulle-objc-list not found in PATH"
+      fail "mulle-objc-list not found in PATH ($PATH)"
    fi
 
    if [ -z "`command -v "mulle-objc-lista"`" ]
    then
-      fail "mulle-objc-lista not found in PATH"
+      fail "mulle-objc-lista not found in PATH ($PATH)"
    fi
 
    #
