migrate some scripts away from mulle-bootstrap to mulle-sde mulle-optimize not fully working yet

diff --git a/mulle-objc-loader-tool b/mulle-objc-loader-tool
--- a/mulle-objc-loader-tool
+++ b/mulle-objc-loader-tool
@@ -48,8 +48,11 @@ usage()
 usage:
    ${MULLE_EXECUTABLE} [options] <name> [dependencies]
 
+   Produces the "objc-loader.inc" file, that declares the dependencies of
+   a library.
+
    Name is the name of the library without prefix or extension and without a
-   "Standalone" suffix. Dependencies are a list of Objective-C dependencies
+   "Standalone" suffix. Dependencies are the Objective-C dependencies
    of this library.
 
    Options:
@@ -63,7 +66,18 @@ EOF
 
 #
 # For each dependency, emit the necessary dependency on the loader
-# except for MulleObjC
+# except for MulleObjC of the form. The input can either be the
+# name (like MulleObjCStandardFoundation) or the location of the
+# objc-loader.inc file (in this case of MulleObjCStandardFoundation). Or it
+# can be combination of both, separated by ':' (historical ?)
+#
+# { @selector( MulleObjCLoader), @selector( <name>) }
+#
+# This tool is mulle-sde agnostic, otherwise we could do this:
+#
+# mulle-sourcetree -e list \
+#   --format "      { @selector( MulleObjCLoader), @selector( %a) },\n" \
+#    --marks all-load --output-raw --output-no-header
 #
 _dump_loader_dependencies()
 {
@@ -76,9 +90,21 @@ _dump_loader_dependencies()
    local categoryid
 
    classid="`${MULLE_OBJC_UNIQUEID} MulleObjCLoader | tail -1`"
+
    while [ $# -ne 0 ]
    do
       case "$1" in
+         "")
+            log_warning "Empty dependency"
+            continue
+         ;;
+
+         *'/objc-loader.inc')
+            depfile="$1"
+            depname="`fast_dirname "${depfile}" `"
+            depname="`fast_basename "${depname}" `"
+         ;;
+
          *:*)
             depfile="`cut -d ':' -f 1 <<< "$1"`"
             depname="`cut -d ':' -f 2 <<< "$1"`"
@@ -92,11 +118,12 @@ _dump_loader_dependencies()
 
       if [ ! -f "${depfile}" ]
       then
-         fail "\"${depfile}\" not found"
+         log_warning "\"${depfile}\" not found"
       fi
+
       if [ -z "${depname}" ]
       then
-         fail "No name given for dependency"
+         fail "No name given or found for dependency \"$1\""
       fi
 
       case "${depname}" in
@@ -114,91 +141,6 @@ _dump_loader_dependencies()
 
       shift
    done
-}
-
-
-_combine_dependencies_inc()
-{
-   log_entry "_combine_dependencies_inc" "$@"
-
-   local depfile
-
-   while [ $# -ne 0 ]
-   do
-      case "$1" in
-         '/'*)
-            depfile="$1"
-         ;;
-
-         *)
-            depfile="${DEPENDENCY_DIR}/include/$1/objc-loader.inc"
-         ;;
-      esac
-
-      if [ ! -f "${depfile}" ]
-      then
-         fail "\"${depfile}\" not found"
-      fi
-
-      cat "${depfile}"
-
-      shift
-   done
-}
-
-
-#
-# the old way
-#
-_do_dump_dylib_dependencies()
-{
-   log_entry "_do_dump_dylib_dependencies" "$@"
-
-   #
-   # First get all classes and categories "below" OS for later removal
-   # Then get all standalone classes, but remove Posix classes and
-   # OS specifica. The remainder are osbase-dependencies
-   #
-   local tmpplus
-   local tmpminus
-
-   tmpplus="`make_tmp_file "plus"`"
-   tmpminus="`make_tmp_file "minus"`"
-
-   redirect_exekutor "${tmpminus}" _combine_dependencies_inc "$@" || fail "combine failed"
-
-   local filename
-   local directory
-
-   filename="`fast_basename "${LIBRARYFILE}"`"
-   directory="`fast_dirname "${LIBRARYFILE}"`"
-
-   # inside cd for mingw, fixed path problems
-   (
-      exekutor cd "${directory}" &&
-      redirect_exekutor "${tmpplus}" "${MULLE_OBJC_LIST}" \
-                                          ${MULLE_TECHNICAL_FLAGS} \
-                                          ${MULLE_OBJC_LIST_FLAGS} \
-                                          -d "${filename}" \
-
-   ) || fail "mulle-objc-list failed"
-   #
-   # remove inherited dependencies from standalone dependencies
-   # also remove MulleObjCLoader class as dependency
-   #
-   if [ ! -z "`cat "${tmpminus}"`" ]
-   then
-      exekutor fgrep -x -v -f "${tmpminus}" "${tmpplus}"
-   else
-      rexekutor cat "${tmpplus}"
-   fi
-
-   if [ "${OPTION_REMOVE_TMP}" = "YES" ]
-   then
-      exekutor rm "${tmpplus}" "${tmpminus}"
-   else
-      log_info "${tmpplus} and ${tmpminus} not removed"
-   fi
 }
 
 
@@ -226,27 +168,22 @@ _dump_dependencies()
 {
    log_entry "_dump_dependencies" "$@"
 
-   local params
-
-   if [ "${OPTION_SDK}" != "Default" ]
-   then
-      params="--sdk '${OPTION_SDK}'"
-   fi
-
-   if [ "${OPTION_CONFIGURATION}" != "Release" ]
-   then
-      params="${params} --configuration '${OPTION_CONFIGURATION}'"
-   fi
-
    [ -z "${DEPENDENCY_DIR}" ] && fail "DEPENDENCY_DIR not set"
 
    local rval
 
+   set -o pipefail
+
    _dump_loader_dependencies "$@" | LC_ALL=C sort | LC_ALL=C sort -u
+   [ $? -ne 0 ] && return 1
+
    if [ ! -z "${LIBRARYFILE}" ]
    then
       _do_dump_static_dependencies | LC_ALL=C sort | LC_ALL=C sort -u
+      [ $? -ne 0 ] && return 1
    fi
+
+   return 0
 }
 
 
@@ -279,7 +216,6 @@ main()
    local OPTION_SDK="Default"
    local OPTION_FORCE="NO"
    local OUTPUT
-
 
    while [ $# -ne 0 ]
    do
@@ -475,4 +411,94 @@ esac
 
 _init "$@"
 main "$@"
+
+
+## +T+
+## +T+ Code Friedhof
+## +T+
+
+# _combine_inc_files()
+# {
+#    log_entry "_combine_inc_files" "$@"
+
+#    local depfile
+
+#    while [ $# -ne 0 ]
+#    do
+#       case "$1" in
+#          '/'*)
+#             depfile="$1"
+#          ;;
+
+#          *)
+#             depfile="${DEPENDENCY_DIR}/include/$1/objc-loader.inc"
+#          ;;
+#       esac
+
+#       if [ ! -f "${depfile}" ]
+#       then
+#          fail "\"${depfile}\" not found"
+#       fi
+
+#       cat "${depfile}"
+
+#       shift
+#    done
+# }
+
+
+# #
+# # the old way.  This combined everything together and then dumped it somehow.
+# # I forget how this was supposed to work really.
+# #
+# _do_dump_dylib_dependencies()
+# {
+#    log_entry "_do_dump_dylib_dependencies" "$@"
+
+#    #
+#    # First get all classes and categories "below" OS for later removal
+#    # Then get all standalone classes, but remove Posix classes and
+#    # OS specifica. The remainder are osbase-dependencies
+#    #
+#    local tmpplus
+#    local tmpminus
+
+#    tmpplus="`make_tmp_file "plus"`"
+#    tmpminus="`make_tmp_file "minus"`"
+
+#    redirect_exekutor "${tmpminus}" _combine_inc_files "$@" || fail "combine failed"
+
+#    local filename
+#    local directory
+
+#    filename="`fast_basename "${LIBRARYFILE}"`"
+#    directory="`fast_dirname "${LIBRARYFILE}"`"
+
+#    # inside cd for mingw, fixed path problems
+#    (
+#       exekutor cd "${directory}" &&
+#       redirect_exekutor "${tmpplus}" "${MULLE_OBJC_LIST}" \
+#                                           ${MULLE_TECHNICAL_FLAGS} \
+#                                           ${MULLE_OBJC_LIST_FLAGS} \
+#                                           -d "${filename}" \
+
+#    ) || fail "mulle-objc-list failed"
+#    #
+#    # remove inherited dependencies from standalone dependencies
+#    # also remove MulleObjCLoader class as dependency
+#    #
+#    if [ ! -z "`cat "${tmpminus}"`" ]
+#    then
+#       exekutor fgrep -x -v -f "${tmpminus}" "${tmpplus}"
+#    else
+#       rexekutor cat "${tmpplus}"
+#    fi
+
+#    if [ "${OPTION_REMOVE_TMP}" = "YES" ]
+#    then
+#       exekutor rm "${tmpplus}" "${tmpminus}"
+#    else
+#       log_info "${tmpplus} and ${tmpminus} not removed"
+#    fi
+# }
 
diff --git a/mulle-objc-unarchive b/mulle-objc-unarchive
--- a/mulle-objc-unarchive
+++ b/mulle-objc-unarchive
@@ -17,13 +17,11 @@ Usage:
    ${MULLE_EXECUTABLE} [options] [library]+
 
    Unarchive the given static libraries and prepare them for optimization.
-   If no libraries are given, ${MULLE_EXECUTABLE} will try to determine the
-   current dependencies folder via mulle-bootstrap and unarchive all static
-   libraries contained therein.
+   If no libraries are given, ${MULLE_EXECUTABLE} will unarchive all static
+   libraries contained in \${DEPENDENCY_DIR}/lib.
 
 Options:
    --unarchive-dir  <dir>    : where to unarchive libraries to
-   --dependencies-dir <dir>  : dependencies folder to scan
 
 EOF
 
@@ -37,7 +35,7 @@ EOF
 # ahem
 lib_pretension()
 {
-   case "${UNAME}" in
+   case "${MULLE_UNAME}" in
       mingw*)
       ;;
 
@@ -50,7 +48,7 @@ lib_pretension()
 
 lib_extension()
 {
-   case "${UNAME}" in
+   case "${MULLE_UNAME}" in
       mingw*)
          echo "lib"
       ;;
@@ -64,7 +62,7 @@ lib_extension()
 
 shlib_extension()
 {
-   case "${UNAME}" in
+   case "${MULLE_UNAME}" in
       darwin)
          echo "dylib"
       ;;
@@ -78,7 +76,7 @@ shlib_extension()
 
 shlib_cflags()
 {
-   case "${UNAME}" in
+   case "${MULLE_UNAME}" in
       darwin)
          echo "-fno-common"
       ;;
@@ -92,7 +90,7 @@ shlib_cflags()
 
 shlib_ldflags()
 {
-   case "${UNAME}" in
+   case "${MULLE_UNAME}" in
       darwin)
          echo "-dynamiclib -all_load -Os -flat_namespace -undefined suppress"
       ;;
@@ -112,7 +110,7 @@ nm_global_undefined_names()
 {
    local filename="$1"
 
-   case "${UNAME}" in
+   case "${MULLE_UNAME}" in
       darwin)
          exekutor nm -g -u -j "${filename}"
       ;;
@@ -133,7 +131,7 @@ create_undefined_linkage_c()
    local symbols
 
    # global, undefined, no type info
-   case "${UNAME}" in
+   case "${MULLE_UNAME}" in
       darwin)
          symbols="`nm_global_undefined_names "${infile}" | sed 's/^_//'`" || exit 1
       ;;
@@ -541,7 +539,7 @@ create_undefined_linkage_c()
 #
 create_undefined_linkage()
 {
-   log_debug "create_undefined_linkage" "$*"
+   log_entry "create_undefined_linkage" "$@"
 
    local infile="$1"
    local outfile="$2"
@@ -573,10 +571,12 @@ create_undefined_linkage()
 
 name_from_library()
 {
+   log_entry "name_from_library" "$@"
+
    local library="$1"
 
    # remove extension
-   library="`extension_less_basename "${library}"`"
+   library="`extensionless_basename "${library}"`"
 
    # remove prefix
    case "${library}" in
@@ -597,6 +597,8 @@ name_from_library()
 
 foldername_from_library()
 {
+   log_entry "foldername_from_library" "$@"
+
    local library="$1"
    local prefix="$2"
 
@@ -612,7 +614,7 @@ foldername_from_library()
 #
 create_shlibs()
 {
-   log_debug "create_shlibs" "$*"
+   log_entry "create_shlibs" "$@"
 
    local folder="$1"
 
@@ -671,7 +673,7 @@ create_shlibs()
 
 unpack_library_into_folder()
 {
-   log_debug "unpack_library_into_folder" "$*"
+   log_entry "unpack_library_into_folder" "$@"
 
    local library="$1"
    local folder="$2"
@@ -700,9 +702,11 @@ unpack_library_into_folder()
 
 remove_all_extensions()
 {
+   log_entry "remove_all_extensions" "$@"
+
    local name
 
-   name="`extension_less_basename "$1"`"
+   name="`extensionless_basename "$1"`"
    if [ "${name}" = "$1" ]
    then
       echo "${name}"
@@ -715,6 +719,8 @@ remove_all_extensions()
 
 emit_loader_source()
 {
+   log_entry "emit_loader_source" "$@"
+
    name="$1"
 
    cat <<EOF
@@ -743,7 +749,7 @@ EOF
 
 prepare_for_optimizer()
 {
-   log_debug "prepare_for_optimizer" "$*"
+   log_entry "prepare_for_optimizer" "$*"
 
    local folder="$1"
    local library="$2"
@@ -764,9 +770,9 @@ prepare_for_optimizer()
    count="`ls -1 "${folder}/MulleObjCLoader"*.o 2> /dev/null | wc -l | awk '{ print $1 }'`"
    case "${count}" in
       1)
-         if [ ! -f "${include}/dependencies.inc" ]
+         if [ ! -f "${include}/objc-loader.inc" ]
          then
-            log_warning "\"${name}\" is not optimizable as \"${include}/dependencies.inc\" was not found"
+            log_warning "\"${name}\" is not optimizable as \"${include}/objc-loader.inc\" was not found"
             exekutor touch "${folder}/.unoptimizable" || exit 1
             return
          fi
@@ -822,10 +828,10 @@ prepare_for_optimizer()
       return 1
    fi
 
-   log_fluff "Loader \"${filename}\" and \"dependencies.inc\" found"
+   log_fluff "Loader \"${filename}\" and \"objc-loader.inc\" found"
 
-   redirect_exekutor "${folder}/dependencies_db.csv" sed 's|^.*// *||' "${include}/dependencies.inc"
-   exekutor egrep '// *58bd58d3' "${include}/dependencies.inc"  | \
+   redirect_exekutor "${folder}/dependencies_db.csv" sed 's|^.*// *||' "${include}/objc-loader.inc"
+   exekutor egrep '// *58bd58d3' "${include}/objc-loader.inc"  | \
       redirect_exekutor "${folder}/loader-dependencies.inc" fgrep -v ';;'
 
    redirect_exekutor "${folder}/MulleObjCLoader+${name}.m" emit_loader_source "${name}"
@@ -841,7 +847,7 @@ prepare_for_optimizer()
 
 unpack_library()
 {
-   log_debug "unpack_library" "$@"
+   log_entry "unpack_library" "$@"
 
    local library="$1"
 
@@ -893,7 +899,7 @@ unpack_library()
 
 unpack_all()
 {
-   log_debug "unpack_all" "$@"
+   log_entry "unpack_all" "$@"
 
    while [ $# -ne 0 ]
    do
@@ -907,7 +913,7 @@ unpack_all()
 # run this with "folder" as PWD
 create_method_csv()
 {
-   log_debug "create_method_csv" "$*"
+   log_entry "create_method_csv" "$*"
 
    local folder="$1"
 
@@ -927,7 +933,7 @@ create_method_csv()
          continue
       fi
 
-      name="`basename "${shlib}" ".${ext}"`"
+      name="`basename -- "${shlib}" ".${ext}"`"
       i="${name}.o"
 
       log_fluff "Create entries for methods of \"$i\"..."
@@ -941,7 +947,7 @@ create_method_csv()
 # run this with "folder" as PWD
 create_class_csv()
 {
-   log_debug "create_class_csv" "$*"
+   log_entry "create_class_csv" "$*"
 
    local folder="$1"
 
@@ -961,7 +967,7 @@ create_class_csv()
          continue
       fi
 
-      name="`basename "${shlib}" ".${ext}"`"
+      name="`basename -- "${shlib}" ".${ext}"`"
       ofile="${name}.o"
 
       log_fluff "Create entries for classes of \"$ofile\"..."
@@ -974,7 +980,7 @@ create_class_csv()
 
 create_method_csv_db()
 {
-   log_debug "create_method_csv_db" "$*"
+   log_entry "create_method_csv_db" "$*"
 
    local folder="$1"
 
@@ -986,7 +992,7 @@ create_method_csv_db()
 
 create_class_csv_db()
 {
-   log_debug "create_class_csv_db" "$*"
+   log_entry "create_class_csv_db" "$*"
 
    local folder="$1"
 
@@ -996,10 +1002,9 @@ create_class_csv_db()
 }
 
 
-
 clean_folder_tmp()
 {
-   log_debug "clean_folder_tmp" "$*"
+   log_entry "clean_folder_tmp" "$*"
 
    local folder="$1"
 
@@ -1013,7 +1018,7 @@ clean_folder_tmp()
 
 create_databases()
 {
-   log_debug "create_databases" "$*"
+   log_entry "create_databases" "$@"
 
    libraries="$1"
 
@@ -1046,7 +1051,8 @@ create_databases()
       then
          log_verbose "Create databases for ${C_MAGENTA}${C_BOLD}${name}${C_VERBOSE} ..."
 
-         cd "${folder}" || return 1
+         rexekutor cd "${folder}" || return 1
+
          create_method_csv_db "${folder}"
          create_class_csv_db "${folder}"
 
@@ -1054,56 +1060,43 @@ create_databases()
          then
             clean_folder_tmp "${folder}"
          fi
-         cd "${old}"
+         rexekutor cd "${old}"
 
-         touch "${folder}/.unarchive_done"
+         exekutor touch "${folder}/.unarchive_done"
       else
          log_fluff "${lib} is C only"
       fi
    done
 
-   touch "${UNARCHIVE_PREFIX}.unarchive_done"
+   exekutor touch "${UNARCHIVE_PREFIX}.unarchive_done"
 
    IFS="${DEFAULT_IFS}"
 }
 
 
-_init()
-{
-   libexecpath="`mulle-bootstrap library-path 2> /dev/null`"
-   if [ -z "${libexecpath}" ]
-   then
-      echo "Fatal Error: Could not find mulle-bootstrap library for ${MULLE_EXECUTABLE}" >&2
-      exit 1
-   fi
-
-   . ${libexecpath}/mulle-bootstrap-logging.sh || internal_fail "mulle-bootstrap-logging.sh not found"
-   . ${libexecpath}/mulle-bootstrap-functions.sh || internal_fail "mulle-bootstrap-functions.sh not found"
-   . ${libexecpath}/mulle-bootstrap-core-options.sh || internal_fail "mulle-bootstrap-core-options.sh not found"
-}
-
-
 unarchive()
 {
-   if [ -z "$*" ]
-   then
-      [ -z "${DEPENDENCIES_DIR}" ] && usage
+   log_entry "unarchive" "$@"
 
-      if [ ! -d "${DEPENDENCIES_DIR}/lib" ]
+   if [ $# -eq 0 ]
+   then
+      [ -z "${DEPENDENCY_DIR}" ] && usage
+
+      if [ ! -d "${DEPENDENCY_DIR}/lib" ]
       then
-         fail "\"${DEPENDENCIES_DIR}/lib\" not found"
+         fail "\"${DEPENDENCY_DIR}/lib\" not found"
       fi
 
       local libext
       local lib
       local i
 
-      log_info "Unpacking libraries found in ${C_RESET}${C_BOLD}${DEPENDENCIES_DIR}/lib${C_INFO} ..."
+      log_info "Unpacking libraries found in ${C_RESET}${C_BOLD}${DEPENDENCY_DIR}/lib${C_INFO} ..."
 
       libext="`lib_extension`"
       IFS="
 "
-      for i in `ls -1 "${DEPENDENCIES_DIR}/lib/"*.${libext}`
+      for i in `ls -1 "${DEPENDENCY_DIR}/lib"/*.${libext}`
       do
          IFS="${DEFAULT_IFS}"
 
@@ -1132,7 +1125,7 @@ main()
 
    while [ $# -ne 0 ]
    do
-      if core_technical_flags "$1"
+      if options_technical_flags "$1"
       then
          shift
          continue
@@ -1168,13 +1161,6 @@ main()
             esac
          ;;
 
-         --dependencies-dir)
-            [ $# -eq 1 ] && fail "missing argument to $1"
-            shift
-
-            DEPENDENCIES_DIR="$1"
-         ;;
-
          -h|--help)
             usage
          ;;
@@ -1191,17 +1177,7 @@ main()
       shift
    done
 
-   core_setup_trace "${MULLE_TRACE}"
-
-   if [ -z "${DEPENDENCIES_DIR}" ]
-   then
-      DEPENDENCIES_DIR="`mulle-bootstrap paths dependencies 2> /dev/null`"
-   fi
-
-   if [ ! -z "${DEPENDENCIES_DIR}" ] && [ -d "${DEPENDENCIES_DIR}/bin" ]
-   then
-      PATH="$PATH:${DEPENDENCIES_DIR}/bin"
-   fi
+   options_setup_trace "${MULLE_TRACE}"
 
    # your code follows here
    if [ -z "`command -v mulle-objc-list`" ]
@@ -1230,14 +1206,34 @@ main()
 }
 
 
-MULLE_EXECUTABLE="`basename -- "$0"`"
-MULLE_ARGUMENTS="$@"
-MULLE_EXECUTABLE_FAIL_PREFIX="${MULLE_EXECUTABLE}"
-MULLE_EXECUTABLE_PID="$$"
+_init()
+{
+   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
+   then
+      MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env "libexec-dir" 2> /dev/null`"
+      [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ] && \
+         echo "mulle-bashfunctions-env not installed" >&2 && \
+         exit 1
+   fi
 
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
 
-set -o pipefail
+   set -o pipefail
+}
 
-_init "$@" # needs params
+#
+# leading backslash ? looks like we're getting called from
+# mingw via a .BAT or so
+#
+case "$PATH" in
+   '\\'*)
+      PATH="`tr '\\' '/' <<< "${PATH}"`"
+   ;;
+esac
 
+#
+# combine all coverage files into one and sort -u it
+#
+
+_init "$@"
 main "$@"
